# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QanQ45r0HarBEPCgWXuf3D_dFqcp4q_O
"""

#generate random numbers
import random
random.randrange(1,1000)