# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QanQ45r0HarBEPCgWXuf3D_dFqcp4q_O
"""

from math import sin,tan,cos
x=sin(60)
y=cos(pi)
z=tan(90)
c=5^8
d=math.sqrt(400)
a=math.floor(23.56)
b=math.ceil(23.56)
print(x)
print(y)
print(z)
print(a)
print(b)
print(c)
print(d)