# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IY4Z4mLJRCTC7SS8IZX8I5I3R38zLiI-
"""

#area of circle
r=int(input())
import math
x=math.pi*r*r
print(x)

